MyShop.WebUI/Controllers/BasketController.cs
using MyShop.Core.Contracts;
using MyShop.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyShop.WebUI.Controllers {
    public class BasketController : Controller {
        public IBasketService basketService;
        public IOrderService orderService;
        public IRepository<Customer> customers;

        public BasketController(IBasketService basketService, IOrderService orderService, IRepository<Customer> customers) {
            this.basketService = basketService;
            this.orderService = orderService;
            this.customers = customers;
        }

        // GET: Basket
        public ActionResult Index() {
            var model = basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToBasket(string Id) {
            basketService.AddToBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromBasket(string Id) {
            basketService.RemoveFromBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public PartialViewResult BasketSummary() {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);

            return PartialView(basketSummary);
        }

        [Authorize]
        public ActionResult CheckOut() {
            Customer customer = customers.Collection().FirstOrDefault(c=>c.Email == User.Identity.Name);
            
            if (customer != null) {
                Order order = new Order() {
                    Email = customer.Email,
                    City = customer.City,
                    State = customer.State,
                    Street = customer.Street,
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    ZipCode = customer.ZipCode
                };

                return View(order);
            }

            return RedirectToAction("Error");
        }

        [HttpPost]
        [Authorize]
        public ActionResult Checkout(Order order) {
            var basketItems = basketService.GetBasketItems(this.HttpContext);
            order.OrderStatus = "Order Created";
            order.Email = User.Identity.Name;

            //Process payment

            order.OrderStatus = "Payment Processed";

            orderService.CreateOrder(order, basketItems);
            basketService.ClearBasket(this.HttpContext);

            return RedirectToAction("ThankYou", new { OrderId = order.Id });
        }

        public ActionResult ThankYou(string OrderId) {
            ViewBag.OrderId = OrderId;

            return View();
        }
    }
}

MyShop.WebUI/Views/Basket/BasketSummary.cshtml
@model MyShop.Core.ViewModels.BasketSummaryViewModel

<ul class="navbar-nav navbar-right pe-4">
    <li><a class="text-decoration-none nav-link" href="@Url.Action("Index", "Basket")">@Model.BasketCount items</a></li>
    <li><a class="text-decoration-none nav-link" href="@Url.Action("Index", "Basket")">@String.Format("{0:c}", Model.BasketTotal)</a></li>
</ul>

MyShop.WebUI/Views/Basket/CheckOut.cshtml
@model MyShop.Core.Models.Order

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Proceed to Payment" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Basket", "Index")
</div>

MyShop.WebUI/Views/Basket/Index.cshtml
@model IEnumerable<MyShop.Core.ViewModels.BasketItemViewModel>

@{
    ViewBag.Title = "Basket";
}

<h2>Basket</h2>

<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            Line Total
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td><img style="height:50px;" class="img" src="~/Content/ProductImages/@item.Image" /></td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @String.Format("{0:c}", item.Price)
        </td>
        <td>
            @String.Format("{0:c}", item.Price * item.Quantity)
        </td>
        <td>
            <a href="@Url.Action("RemoveFromBasket", "Basket", new { Id=item.Id })" class="btn btn-danger">Remove</a>
        </td>
    </tr>
}
    <tr>
        <td colspan="4" style="text-align:right"><strong>Basket Total</strong></td>
        <td>@String.Format("{0:c}", (from p in Model select p.Price * p.Quantity).Sum())</td>
        <td><a href="@Url.Action("Checkout", "Basket")">Checkout</a></td>
    </tr>
</table>

MyShop.WebUI/Views/Basket/ThankYou.cshtml
@{
    ViewBag.Title = "Thank You";
}

<h2>Thank You</h2>
<p>Thank you for your order.</p>
<br /><br />
<p>Your Order Id - @ViewBag.OrderId</p>
<br /><br />